name: Run tests

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - 'master'
    paths:
      - '**.vue'
      - '**.ts'

env:
  HUSKY: 0

jobs:
  js-tests:
    name: Run JS tests
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
  
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Running tests
        run: bun run test
